services:
  postgres:
    container_name: postgresql17.2
    image: postgres
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: plataforma
    ports:
      - "5432:5432"

  pgadmin:
    container_name: PGADM
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: l_fp9999@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"